import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/core/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#141c27",
        "on-tertiary-fixed-variant": "#3f4753",
        "on-primary-fixed-variant": "#673d00",
        "tertiary-fixed": "#dbe3f2",
        "on-tertiary": "#29313c",
        "on-secondary": "#4d2600",
        "surface-container-lowest": "#0b0e15",
        "surface-dim": "#10131a",
        "error-container": "#93000a",
        "on-primary": "#482900",
        "surface-container": "#1d1f27",
        "on-error-container": "#ffdad6",
        "surface-bright": "#363941",
        "primary-fixed": "#ffddbb",
        "secondary-fixed-dim": "#ffb77d",
        "outline-variant": "#514438",
        "surface": "#10131a",
        "on-secondary-container": "#432100",
        "primary": "#ffc27e",
        "secondary-container": "#d97707",
        "secondary-fixed": "#ffdcc3",
        "on-tertiary-container": "#3d4551",
        "surface-container-highest": "#32353d",
        "primary-container": "#e8a455",
        "surface-container-low": "#191b23",
        "error": "#ffb4ab",
        "surface-variant": "#32353d",
        "secondary": "#ffb77d",
        "primary-fixed-dim": "#ffb868",
        "tertiary-fixed-dim": "#bfc7d6",
        "on-error": "#690005",
        "on-secondary-fixed": "#2f1500",
        "background": "#10131a",
        "surface-tint": "#ffb868",
        "on-primary-container": "#643b00",
        "on-background": "#e1e2ec",
        "on-primary-fixed": "#2b1700",
        "inverse-on-surface": "#2d3038",
        "inverse-surface": "#e1e2ec",
        "on-surface-variant": "#d6c3b3",
        "on-secondary-fixed-variant": "#6e3900",
        "outline": "#9e8e7f",
        "surface-container-high": "#272a32",
        "on-surface": "#e1e2ec",
        "tertiary": "#c6cddc",
        "inverse-primary": "#875204",
        "tertiary-container": "#aab2c1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "1.5rem",
        "space-sm": "0.75rem",
        gutter: "2rem",
        "space-xl": "4.5rem",
        "space-md": "1.5rem",
        "space-lg": "2.5rem",
        "space-xs": "0.375rem",
        margin: "4rem",
        "gutter-mobile": "1rem",
      },
      fontFamily: {
        "display-brand": ["Playfair Display", "serif"],
        "body-sm": ["Montserrat", "sans-serif"],
        "label-counter": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "display-hero": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "editorial-quote": ["Playfair Display", "serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "label-nav": ["Montserrat", "sans-serif"],
        "display-hero-mobile": ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "display-brand": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "0.05em", fontWeight: "400" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.375rem", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-counter": ["0.875rem", { lineHeight: "1rem", letterSpacing: "0.25em", fontWeight: "500" }],
        "body-lg": ["1.125rem", { lineHeight: "1.875rem", letterSpacing: "0.01em", fontWeight: "400" }],
        "display-hero": ["5.5rem", { lineHeight: "5.25rem", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-lg-mobile": ["2rem", { lineHeight: "2.25rem", letterSpacing: "-0.01em", fontWeight: "800" }],
        "headline-md": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "0.02em", fontWeight: "700" }],
        "headline-sm": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "0.05em", fontWeight: "600" }],
        "editorial-quote": ["1.5rem", { lineHeight: "2.25rem", letterSpacing: "0.02em", fontWeight: "400" }],
        "headline-lg": ["3rem", { lineHeight: "3.25rem", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["0.9375rem", { lineHeight: "1.6rem", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-nav": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.2em", fontWeight: "600" }],
        "display-hero-mobile": ["2.75rem", { lineHeight: "3rem", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};

export default config;
